/**
 * Single import point for all app icons.
 * All icons are stroke-style SVGs from components/icons.tsx.
 */
export {
  HomeIcon,
  TrophyIcon,
  ChartIcon,
  PersonIcon,
  GearIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ArrowUpRightIcon,
  ArrowUpIcon,
  PlusIcon,
  XIcon,
  CheckIcon,
  LockIcon,
  MicIcon,
  PenIcon,
  HeadphoneIcon,
  BookIcon,
  SpeakIcon,
  BellIcon,
  LightningIcon,
  FlameIcon,
  SendIcon,
  GlobeIcon,
  SunIcon,
  TypeIcon,
  StarIcon,
  LogOutIcon,
  HelpCircleIcon,
  PhoneIcon,
  ExternalLinkIcon,
  TrashIcon,
  FileTextIcon,
  SearchIcon,
  CalendarIcon,
  AwardIcon,
  RefreshIcon,
  TimerIcon,
  CameraIcon,
  CreditCardIcon,
  UsersIcon,
  type IconProps,
} from '@/components/icons';
